FROM golang:1.21-bookworm

WORKDIR /app

# Instalar dependências do sistema (ZMQ)
RUN apt-get update && apt-get install -y \
    pkg-config \
    libzmq3-dev \
    && rm -rf /var/lib/apt/lists/*
    
# Copiar código GO
COPY . .

# Criar go.mod se não existir e adicionar dependências
RUN if [ ! -f "go.mod" ]; then \
        go mod init reference-server && \
        go get github.com/pebbe/zmq4 && \
        go get github.com/vmihailenco/msgpack/v5; \
    fi

# Inicializar módulo GO e baixar dependências
RUN go mod tidy


# Compilar
RUN go build -o reference reference/main.go

CMD ["go", "run", "reference/main.go"]