FROM golang:1.21-bookworm

WORKDIR /app

# Instalar dependências do sistema (ZMQ)
RUN apt-get update && apt-get install -y \
    pkg-config \
    libzmq3-dev \
    && rm -rf /var/lib/apt/lists/*
    
# Copiar go.mod
COPY go.mod ./

# Baixar dependências
RUN go get github.com/pebbe/zmq4@v1.2.9 && \
    go get github.com/vmihailenco/msgpack/v5@v5.4.1

# Copiar código GO (arquivos específicamente para evitar conflito)
COPY reference reference
COPY common common
COPY clock clock

# Compilar - output como reference_server
RUN go build -o reference_server ./reference/main.go

EXPOSE 5559

CMD ["./reference_server"]