FROM python:3.9-alpine
WORKDIR /app

RUN pip install pyzmq msgpack

COPY ./servidor.py .
COPY persistence.py .
COPY common/ ./common/

RUN mkdir -p /app/data

CMD ["python", "servidor.py"]
