FROM golang:1.21-bookworm

WORKDIR /app

# Copiar código GO
COPY go/reference/main.go .
COPY go/common/ ./common/
COPY go/clock/ ./clock/

# Inicializar módulo GO e baixar dependências
RUN go mod init reference-server
RUN go get github.com/vmihailenco/msgpack/v5
RUN go get github.com/pebbe/zmq4

# Compilar
RUN go build -o reference main.go

CMD ["./reference"]