FROM gcc:12-bookworm

WORKDIR /app

# Instalar dependências
RUN apt-get update && apt-get install -y \
    libzmq3-dev \
    libreadline-dev \
    pkg-config \
    libmsgpack-dev \
    && rm -rf /var/lib/apt/lists/*

# Copiar código fonte
COPY auto_client.c .
COPY Makefile .
COPY common/ ./common/

# Compilar
RUN gcc -Wall -g -std=c99 -pthread -I./common -o auto_client auto_client.c common/message_protocol.c common/logical_clock.c -lzmq -lmsgpackc

CMD ["./auto_client"]