FROM gcc:12-bookworm

WORKDIR /app

# Instalar dependências (incluindo msgpack)
RUN apt-get update && apt-get install -y \
    libzmq3-dev \
    libmsgpack-dev \
    libreadline-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Compilar o cliente com MessagePack
COPY client.c .
COPY common/ ./common/

RUN gcc -Wall -g -std=c99 -pthread -o client client.c common/message_protocol.c common/logical_clock.c -lzmq -lmsgpackc -lreadline
CMD ["./client"]